version: '3.8'
services:
  ad-bot:
    build: .
    container_name: ad-reset-bot
    restart: unless-stopped
    env_file:
      - .env
    # если нужны volume’ы для логов:
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-net

networks:
  bot-net:
    driver: bridge
